"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
format = """
[ÓÇ∂](color_orange)\
$os\
[ÓÇ¥ ](fg:color_orange bg:color_bg1)\
$username\
[ÓÇ∞](fg:color_bg1 bg:color_aqua)\
$directory\
[ÓÇ∞](fg:color_aqua bg:color_blue)\
$git_branch\
$git_status\
[ÓÇ∞](fg:color_blue bg:color_blue2)\
$c\
$rust\
$golang\
$php\
$java\
$haskell\
$python\
[ÓÇ∞](fg:color_blue2 bg:color_bg3)\
$docker_context\
$conda\
[ÓÇ∞](fg:color_bg3 bg:color_bg1)\
$time\
[ÓÇ¥ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_fg = '#ebdbb2'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_blue2 = '#076678'
color_aqua = '#68936f'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "Û∞ç≤"
Ubuntu = "Û∞ïà"
SUSE = "Ôåî"
Raspbian = "Û∞êø"
Mint = "Û∞£≠"
Macos = "Û∞Äµ"
Manjaro = "Ôåí"
Linux = "‚ô•"
Gentoo = "Û∞£®"
Fedora = "Û∞£õ"
Alpine = "ÔåÄ"
Amazon = "Ôâ∞"
Android = "Óúé"
Arch = "Œ¶"
Artix = ""
EndeavourOS = "ÔÜó"
CentOS = "ÔåÑ"
Debian = "Û∞£ö"
Redhat = "Û±Ñõ"
RedHatEnterprise = "Û±Ñõ"
Pop = "Ôå™"

[username]
show_always = true
style_user = "bg:color_bg1 fg:color_fg0"
style_root = "bg:color_bg1 fg:color_fg0"
format = '[$user ]($style)'

[directory]
style = "bold fg:#000000 bg:color_aqua"
format = "[ $path ]($style)"
truncation_length = 50
truncation_symbol = "*/"

[directory.substitutions]
"Documents" = "üñπ"
"Downloads" = "‚á©"
"Music" = "‚ô™‚ô´"
"Pictures" = "üñª"
"Developer" = "‚¶ì‚ãà"

[git_branch]
symbol = "‚µñ"
style = "bg:color_aqua"
format = '[[ $branch $symbol ](fg:color_fg0 bg:color_blue)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = "Óòû "
style = "bg:color_blue2"
format = '[[ $symbol](fg:color_fg0 bg:color_blue2)]($style)'

[rust]
symbol = "Óû®"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = "Óòß"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = "Óòà"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = "Óâñ"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = "Óòü"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = "ÓòÜ"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = "Ôåà"
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[ $time](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[ ‚ùØ](bold fg:color_fg0)'
error_symbol = '[ ‚ùØ](bold fg:color_red)'
vimcmd_symbol = '[ ‚ùÆ](bold fg:color_bg1)'
vimcmd_replace_one_symbol = '[Ôê¥](bold fg:color_purple)'
vimcmd_replace_symbol = '[Ôê¥](bold fg:color_purple)'
vimcmd_visual_symbol = '[Ôê¥](bold fg:color_yellow)'
